server:
  port: 0

spring:
  application:
    name: categories-service
  data:
    mongodb:
      uri: mongodb+srv://milo:F1d3l109@cluster0.x7dml.mongodb.net/mongotraining?retryWrites=true&w=majority

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uui}

app:
  testProp: Test propertie updated and adding more text